name: test-irc

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2  # Güncellenmiş checkout eylemi
		
      - name: build application
        run: make all
